spring:
  jpa:
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc.batch_size: 10
        order_inserts: true
        order_updates: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

oauth:
  kakao:
    client-id: ENC(EsfXRVa2XsZTVTJruQdsj0B6vAA4GfSfDJ6Ow60HGBjP2lniOC7Q383lCKJutTie)
    client-secret: ENC(EsfXRVa2XsZTVTJruQdsj0B6vAA4GfSfDJ6Ow60HGBjP2lniOC7Q383lCKJutTie)
    oauth-endpoint-uri: https://kauth.kakao.com/oauth/authorize
    oauth-token-issue-uri: https://kauth.kakao.com/oauth/token
    oauth-userinfo-uri: https://kapi.kakao.com/v2/user/me
    response-type: code

jwt:
  secret: potenday
  access-time-sec: 600
  refresh-time-sec: 86400