spring:
  datasource:
    url: ENC(GcGrgOnI6WEIm1yt4hCqMvNJrmDjnF/wPHTskMPoB5Ke0FQBzTlBJx5EnpjGbjt90sr+GV01lFQNBKl6wLs8Xg==)
    username: ENC(dltaReNsKvakVzwihkixNLVnwIrN4Hrf)
    password: ENC(G1jv1nj5+8IT556IHyRvUhjpTtH6fuuI)

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc.batch_size: 10
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQL8Dialect

oauth:
  kakao:
    client-id: ENC(EsfXRVa2XsZTVTJruQdsj0B6vAA4GfSfDJ6Ow60HGBjP2lniOC7Q383lCKJutTie)
    client-secret: ENC(EsfXRVa2XsZTVTJruQdsj0B6vAA4GfSfDJ6Ow60HGBjP2lniOC7Q383lCKJutTie)
    oauth-endpoint-uri: https://kauth.kakao.com/oauth/authorize
    oauth-token-issue-uri: https://kauth.kakao.com/oauth/token
    oauth-userinfo-uri: https://kapi.kakao.com/v2/user/me
    response-type: code